[返回汇总文档](./main.ipynb)

In [13]:
import numpy as np

- NumPy 数组基础操作

1. 创建基础数组：


  - 创建一个长度为10的一维数组，元素为0-9（模拟10天的简单时序数据，如每日基础流量）；

  - 创建一个3行5列的二维数组，元素为1-15（模拟3组、每组5天的时序数据，如3个产品的5日销量）；

  - 创建一个全为1的一维数组，长度为7（模拟一周的固定基准值）。

In [27]:
arr1 = np.arange(0,10,1)
arr2 = np.arange(1,16,1).reshape(3,5)
arr3 = np.ones(7, dtype=int, order='C')

In [46]:
arr1

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])


2. 数组索引与切片（时序数据常用，重点练）：


  - 对第1题创建的“0-9一维数组”，切片获取前5个元素（前5天数据）、后3个元素（后3天数据）；

  - 对第1题创建的“3行5列二维数组”，获取第2行所有元素（第2个产品的全部5日销量）、获取所有行的第3列元素（3个产品的第3天销量）；

  - 用索引修改数组元素：将一维数组中索引为3的元素（第4天数据）改为100，模拟时序数据中的异常值。

In [41]:
# arr1[0:5]
# arr1[-3:]
# arr2[1,:]
# arr2[:,2]
arr1[3] = 100


3. 数组形状操作（适配后续时序数据格式）：


  - 将第1题创建的“0-9一维数组”，reshape为2行5列的二维数组（模拟将10天数据按“每5天一组”拆分）；

  - 将3行5列的二维数组，展平为一维数组（模拟将多组时序数据合并为单一时序序列）。

In [45]:
# arr1.reshape(2,5)
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])


4. 数组运算（时序数据基础统计）：


  - 计算“0-9一维数组”的均值、最大值、最小值（模拟计算10天数据的基础统计量）；

  - 将“0-9一维数组”与“全为1的7元素数组”进行广播运算（加法），模拟时序数据的基准值偏移；

  - 计算3行5列二维数组中，每一行的求和（模拟计算每个产品5日总销量）。

In [59]:
# np.mean(arr1)
# np.max(arr1)
# np.min(arr1)
# np.add.outer(arr1,arr3)
# arr2
np.sum(arr2,axis=1)

array([15, 40, 65])


进阶选做题（贴合时序预处理，提前铺垫）

1. 模拟时序缺失值处理：创建一个包含NaN值的一维数组（如[1,2,np.nan,4,5,np.nan,7]），用NumPy方法将NaN值替换为数组的均值（后续时序缺失值处理基础）。

2. 模拟时序数据差分（后续ARIMA模型基础）：对“0-9一维数组”，计算相邻两个元素的差值（即后一个元素减前一个元素），得到差分数组。

3. 数组拼接（多时序数据合并）：创建两个一维数组（分别模拟两组不同时段的时序数据，如[10,11,12]和[13,14,15]），将其拼接为一个更长的一维数组。

In [75]:
ln = [7,8,9,np.nan,6,8,10,np.nan]
arrn = np.array(ln, dtype=float, order='C')
arrn1 = np.where(np.isnan(arrn),np.nanmean(arrn),arrn)
# np.nanmean(arrn)
arrn1
np.diff(arrn1)
np.concatenate((arr1,arrn1),axis = 0)

array([  0.,   1.,   2., 100.,   4.,   5.,   6.,   7.,   8.,   9.,   7.,
         8.,   9.,   8.,   6.,   8.,  10.,   8.])

- Pandas：Series、DataFrame、读取 csv/excel

（一）Series 相关作业
1. 使用列表 [12, 34, 23, 56, 38] 创建一个 Series，允许索引自动生成，打印该 Series。


2. 手动指定索引为 ['周一','周二','周三','周四','周五']，重新创建上述数值的 Series（模拟一周的每日基础数据），打印该 Series。

3. 分别打印该 Series 的「值（values）」「索引（index）」「数据类型（dtype）」。

4. 通过索引，取出「周三」对应的数值。

5. 筛选出该 Series 中，数值大于 30 的数据（模拟筛选异常/达标数据）。

（二）DataFrame 相关作业

1. 使用如下数据，创建一个 DataFrame（模拟4天的时序业务数据）：
      ```python
      # 数据说明：日期、每日销量、每日访客数
      data = {
          "日期": ['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04'],
          "销量": [150, 200, 180, 220],
          "访客": [300, 450, 380, 520]
      }
      ```


2. 查看该 DataFrame 的基础信息：

  - 打印前3行数据（head(3)）

  - 查看数据基本信息（info()）

  - 查看数据统计描述（describe()，含均值、最值等）

3. 单独取出「销量」列，打印该列并判断其数据类型是否为 Series。

4. 筛选出「销量 > 180」的所有行（模拟筛选高销量日期数据）。

5. 为该 DataFrame 添加新列「转化率」，计算公式：转化率 = 销量 / 访客（保留3位小数）。

（三）csv / excel 文件读写作业

1. 读取 csv 文件：


  - 方法1：自己创建一个简单的 csv 文件（用Excel新建，输入2-3列数据，保存为 .csv 格式），用 pd.read_csv() 读取，打印读取结果。

  - 方法2：直接读取网络公开csv数据（无需手动创建），代码参考：
          ```python
          # 读取公开的时序测试数据（气温数据）
          df_csv = pd.read_csv("https://raw.githubusercontent.com/datasets/weather/master/data/nyc_centralpark_weather.csv")
          print(df_csv.head())
          ```


2. 读取 excel 文件：


  - 自己创建一个简单的 excel 文件（2-3列数据，保存为 .xlsx 格式），用 pd.read_excel() 读取，指定 sheet_name（默认sheet1），打印读取结果。

3. 保存文件：将第二部分（DataFrame作业）中创建的 DataFrame，分别保存为 result.csv 和 result.xlsx（保存路径可自定义，如桌面）。

4. 验证保存结果：重新读取刚刚保存的 result.csv 和 result.xlsx，打印前2行，确认数据保存无误。

三、进阶选做题（贴合时序预处理，提前铺垫）

1. 将 DataFrame 中的「日期」列，转为时间类型（使用 pd.to_datetime()），打印转换后的数据类型。

2. 将转换后的「日期」列，设置为 DataFrame 的索引（模拟标准时序数据格式）。

3. 通过索引，筛选出「2025-01-03」这一天的所有数据。

4. 模拟缺失值处理：


  - 给 DataFrame 手动添加一行含 NaN 的数据（如：日期='2025-01-05'，销量=NaN，访客=400，转化率=NaN）。

  - 查看 DataFrame 中的缺失值（使用 isnull().sum()）。

  - 将缺失值填充为对应列的均值（销量列用销量均值填充，转化率列用转化率均值填充）。