[返回汇总文档](./main.ipynb)

In [13]:
import numpy as np

1. 创建基础数组：


  - 创建一个长度为10的一维数组，元素为0-9（模拟10天的简单时序数据，如每日基础流量）；

  - 创建一个3行5列的二维数组，元素为1-15（模拟3组、每组5天的时序数据，如3个产品的5日销量）；

  - 创建一个全为1的一维数组，长度为7（模拟一周的固定基准值）。

In [27]:
arr1 = np.arange(0,10,1)
arr2 = np.arange(1,16,1).reshape(3,5)
arr3 = np.ones(7, dtype=int, order='C')

In [46]:
arr1

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])


2. 数组索引与切片（时序数据常用，重点练）：


  - 对第1题创建的“0-9一维数组”，切片获取前5个元素（前5天数据）、后3个元素（后3天数据）；

  - 对第1题创建的“3行5列二维数组”，获取第2行所有元素（第2个产品的全部5日销量）、获取所有行的第3列元素（3个产品的第3天销量）；

  - 用索引修改数组元素：将一维数组中索引为3的元素（第4天数据）改为100，模拟时序数据中的异常值。

In [41]:
# arr1[0:5]
# arr1[-3:]
# arr2[1,:]
# arr2[:,2]
arr1[3] = 100


3. 数组形状操作（适配后续时序数据格式）：


  - 将第1题创建的“0-9一维数组”，reshape为2行5列的二维数组（模拟将10天数据按“每5天一组”拆分）；

  - 将3行5列的二维数组，展平为一维数组（模拟将多组时序数据合并为单一时序序列）。

In [45]:
# arr1.reshape(2,5)
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])


4. 数组运算（时序数据基础统计）：


  - 计算“0-9一维数组”的均值、最大值、最小值（模拟计算10天数据的基础统计量）；

  - 将“0-9一维数组”与“全为1的7元素数组”进行广播运算（加法），模拟时序数据的基准值偏移；

  - 计算3行5列二维数组中，每一行的求和（模拟计算每个产品5日总销量）。

In [59]:
# np.mean(arr1)
# np.max(arr1)
# np.min(arr1)
# np.add.outer(arr1,arr3)
# arr2
np.sum(arr2,axis=1)

array([15, 40, 65])


进阶选做题（贴合时序预处理，提前铺垫）

1. 模拟时序缺失值处理：创建一个包含NaN值的一维数组（如[1,2,np.nan,4,5,np.nan,7]），用NumPy方法将NaN值替换为数组的均值（后续时序缺失值处理基础）。

2. 模拟时序数据差分（后续ARIMA模型基础）：对“0-9一维数组”，计算相邻两个元素的差值（即后一个元素减前一个元素），得到差分数组。

3. 数组拼接（多时序数据合并）：创建两个一维数组（分别模拟两组不同时段的时序数据，如[10,11,12]和[13,14,15]），将其拼接为一个更长的一维数组。

In [75]:
ln = [7,8,9,np.nan,6,8,10,np.nan]
arrn = np.array(ln, dtype=float, order='C')
arrn1 = np.where(np.isnan(arrn),np.nanmean(arrn),arrn)
# np.nanmean(arrn)
arrn1
np.diff(arrn1)
np.concatenate((arr1,arrn1),axis = 0)

array([  0.,   1.,   2., 100.,   4.,   5.,   6.,   7.,   8.,   9.,   7.,
         8.,   9.,   8.,   6.,   8.,  10.,   8.])